
<!DOCTYPE html>
<html  lang="en-us">
<?php include('assets/templates/partials/head_section.html'); ?>

<body>
    <!-- Navbar -->
    <?php include('assets/templates/partials/navbar.html'); ?>
    <!-- // Navbar -->
    <main class="container">

        <section class="single-content">

            <div>
                <h2 class="post-title">
                    <?php echo htmlspecialchars($post['title']); ?> by

                        <a href="author_posts.php?author=<?php echo htmlspecialchars($post['user_id']); ?>">
                            <?php echo htmlspecialchars($post['author']); ?>
                        </a>
                </h2>
            </div>

            <article class="full-post-div">

                <header class="page_set">
                    <select class="setFontFamily"> 
                            <option value="Arial">Arial</option>
                            <option value="Roboto">Roboto</option>
                            <option value="opendyslexic">Open Dyslexic</option>
                            <option value="Comic Sans MS, Comic Sans" >Comic Sans</option>
                            <option value="Verdana" >Verdana</option>
                            <option value="Ubuntu" >Ubuntu</option>
                            <option value="Ubuntu Condensed">Ubuntu Condensed</option>
                            <option value="Franklin Gothic">Franklin Gothic</option>
                            <option value="Georgia">Georgia</option>
                        </select>
                    <select class="setColor"> 
                            <option value="#000">Black</option> 
                            <option value="#9370DB">MediumPurple</option> 
                            <option value="#2E8B57">SeaGreen</option> 
                            <option value="#2F4F4F">DarkSlateGray</option> 
                            <option value="#778899">LightSlateGray</option> 
                            <option value="#800000">Maroon</option> 
                            <option value="#6A5ACD">SlateBlue</option> 
                            <option value="#BC8F8F">RosyBrown</option> 
                            <option value="#F4A460">SandyBrown</option> 
                            <option value="#F5F5DC">Beige</option> 
                            <option value="#F5F5F5">WhiteSmoke</option> 
                        </select>
                    <select class="setSize"> 
                            <option value="12px">12pt</option> 
                            <option value="14px">14pt</option>
                            <option value="16px">16pt</option> 
                            <option value="18px">18pt</option>
                            <option value="20px">20pt</option> 
                            <option value="22px">22pt</option>
                            <option value="24px">25pt</option> 
                            <option value="28px">30pt</option>
                            <option value="32px">30pt</option> 
                        </select>

                    <select class="setBGColor"> 
                            <option>white</option> 
                            <option>MediumPurple</option> 
                            <option>SeaGreen</option> 
                            <option>DarkSlateGray</option> 
                            <option>LightSlateGray</option> 
                            <option>Maroon</option> 
                            <option>SlateBlue</option> 
                            <option>RosyBrown</option> 
                            <option>SandyBrown</option> 
                            <option>Beige</option> 
                            <option>WhiteSmoke</option> 
                        </select>
                    <select class="setMaxWidth"> 
                            <option>Max width</option> 
                            <option>90%</option> 
                            <option>80%</option> 
                            <option>70%</option>
                            <option>60%</option>
                            <option>50%</option>
                        </select>
                    <select class="nightMode">
                            <option>Light</option> 
                            <option>Dark</option> 
                        </select>
                </header>

                <div class="post-body-div">
                    <p>
                        <?php echo nl2br(htmlspecialchars($post['body'])); ?>
                    </p>
                </div>
            </article>
        </section>
    </main>
    <!-- Footer -->
        <?php require( 'assets/templates/partials/footer.html'); ?>
    <!-- // Footer -->
    <script src="assets/js/main.js"></script>
    <!--js script for selects options  -->
    <script src="assets/js/single_post.js"></script>
</body>



</html>
